name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  clippy-and-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/cache
      - run: |
          rustup toolchain add 1.69.0
          rustup override set 1.69.0
          rustup component add clippy --toolchain 1.69.0-x86_64-unknown-linux-gnu
          rustup component add rustfmt --toolchain 1.69.0-x86_64-unknown-linux-gnu
      - name: fmt
        run: |
          cargo fmt --all -- --check
      - name: clippy
        # Check by `clippy` even if the previous step fails
        if: success() || failure()
        run: |
          cargo clippy --all -- -D warnings
