name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  clippy-and-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/cache
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.69.0
            override: true
            components: rustfmt, clippy
      - name: fmt
        run: |
          cargo fmt --all -- --check
      - name: clippy
        # Check by `clippy` even if the previous step fails
        if: success() || failure()
        run: |
          cargo clippy --all -- -D warnings
